import 'package:sameway/features/find_ride/find_ride_flow.dart';

/// Catalog / offline-only sample listings — not used when API is enabled.
abstract final class DevFindRideSamples {
  static const List<FindRideListing> listings = [
    FindRideListing(
      id: '1',
      driverName: 'Karim R.',
      driverFullName: 'Karim Rahman',
      driverInitial: 'K',
      company: 'Grameenphone',
      from: 'Uttara Sec 4',
      to: 'Motijheel',
      departTime: '8:25 AM',
      arriveTime: '~9:15 AM',
      seats: 2,
      overlap: 94,
      rides: 47,
      onTimePct: 96,
      vehicleLabel: '🚗 Toyota Allion',
      vehicleDetail: 'White · 4 seats',
      pickupLabel: 'Your pickup (3 min walk)',
      pickupDetail: 'Uttara Bus Stand · Gate 2',
      driverNote:
          '"No smoking. Music ok. Usually early. Cost split by mutual agreement."',
      coRiderName: 'Sadia M.',
      coRiderInitial: 'S',
    ),
    FindRideListing(
      id: '2',
      driverName: 'Nasrin A.',
      driverFullName: 'Nasrin Ahmed',
      driverInitial: 'N',
      company: 'Banglalink',
      from: 'Uttara-10',
      to: 'Motijheel',
      departTime: '8:35 AM',
      arriveTime: '~9:20 AM',
      seats: 1,
      overlap: 89,
      rides: 31,
      onTimePct: 94,
      vehicleLabel: '🚗 Honda City',
      vehicleDetail: 'Silver · 4 seats',
      pickupLabel: 'Your pickup (5 min walk)',
      pickupDetail: 'Abdullahpur Mor',
      driverNote: '"Prefer quiet rides. AC on."',
    ),
    FindRideListing(
      id: '3',
      driverName: 'Jahid K.',
      driverFullName: 'Jahid Khan',
      driverInitial: 'J',
      company: 'BRAC',
      from: 'Abdullahpur',
      to: 'Motijheel',
      departTime: '8:15 AM',
      arriveTime: '~9:05 AM',
      seats: 2,
      overlap: 78,
      rides: 22,
      onTimePct: 91,
      vehicleLabel: '🏍 Yamaha FZ',
      vehicleDetail: 'Black · 1 seat',
      pickupLabel: 'Your pickup (4 min walk)',
      pickupDetail: 'Uttara House Building',
      driverNote: '"Helmet provided. One pillion only."',
      isBike: true,
    ),
  ];
}
